#!/bin/bash

WEBROOT=/var/www/html
# Lets Encrypt
if [ -z "$WEBROOT" ] || [ -z "$EMAIL" ] || [ -z "$DOMAIN" ]; then
 echo "You need the \$WEBROOT, \$GIT_EMAIL and the \$DOMAIN Variables"
else
 certbot certonly --webroot -w $WEBROOT -d $DOMAIN --email $EMAIL --agree-tos --quiet

  if [ -d /etc/letsencrypt/live/${DOMAIN} ]; then
    ln -s /etc/nginx/sites-available/default-ssl.conf /etc/nginx/sites-enabled/
    # change nginx for webroot and domain name
    sed -i "s/##DOMAIN##/${DOMAIN}/g" /etc/nginx/sites-enabled/default-ssl.conf
    sed -i "s#root /var/www/html;#root ${WEBROOT};#g" /etc/nginx/sites-available/default-ssl.conf
    sed -i "s/#return 301/return 301/g" /etc/nginx/sites-available/default.conf
    supervisorctl restart nginx
  else
    echo "Lets Encrypt failed!"
  fi
fi

